[project]
name = "space-deck-builder-simulator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.4",
    "pygame>=2.6.1",
    "torch>=2.6.0",
]
